# Generated by Django 2.0.6 on 2018-06-29 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_venda',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
