# Generated by Django 2.0.6 on 2018-07-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180630_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-data_venda',)},
        ),
    ]
