# Generated by Django 2.0.6 on 2018-06-29 19:08

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_data_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=datetime.date.today)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
