# Generated by Django 2.0.6 on 2018-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parcela_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ('data_recebimento',)},
        ),
        migrations.AddField(
            model_name='item',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
    ]
