# Generated by Django 2.0.6 on 2018-07-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
